AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  Save-Concept:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::009241727190:role/service-role/Save-Concept-role-bdx7ku3p'
      Runtime: python3.6
      Timeout: 3
